/* https://projecteuler.net/problem=2
 * 
 * Title: Even Fibonacci numbers
 * 
 * Description: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

var watch = new System.Diagnostics.Stopwatch();

watch.Start();

Console.WriteLine(Fibonacci(1, 2, 4000000, 2));

static int Fibonacci(int x, int y, int max, int sum)
{
    int nextNumber = x + y;

    if(nextNumber > max)
    {
        return sum;
    }
    else
    {
        if (nextNumber % 2 == 0)
        {
            sum += nextNumber;
        }

        return Fibonacci(y, nextNumber, max, sum);
    }
}


watch.Stop();

Console.WriteLine($"Execution Time: {watch.ElapsedMilliseconds} ms");